### ISSUE TITLE
Yuzu Android on Surface Duo 2 shows rotated and squashed screen

### ISSUE THREAD

**Issue by tovarishes** [yuzu-emu/yuzu-android#11]
Installed the latest Yuzu EA on a surface duo 2 but the screen is not shown in landscape but a squashed portrait while the on screen buttons are still landscape.
Another user has the same issue
https://www.reddit.com/r/surfaceduo/comments/13xke8q/running_yuzu_on_duo_2/

**Comment by tovarishes** [comment]
My case is actually like issue #10 
https://github.com/yuzu-emu/yuzu-android/issues/10

**Comment by MonsterDruide1** [comment]
Yes, seems to be the same issue as the one you pointed out. To avoid duplicate issues, please close this one, and add your info/subscribe to the other one. This way, all information and work can be collected in a single location.

**Comment by tovarishes** [comment]
Closed as duplicate
